# see https://blog.kloia.com/micro-docker-images-for-go-applications-8a8701130c01
# STEP 1 build executable binary
FROM golang as builder
COPY . $GOPATH/src/github.com/hamilton-lima/robolucha-services/
WORKDIR $GOPATH/src/github.com/hamilton-lima/robolucha-services/
#get dependancies
#you can also use dep
RUN go get -d -v

#build the binary
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/bin/publisher
RUN chmod +x /go/bin/publisher

# STEP 2 build a small image
# start from scratch
FROM scratch
EXPOSE 5000
# Copy our static executable
COPY --from=builder /go/bin/publisher /go/bin/publisher
ENTRYPOINT ["/go/bin/publisher"]
